// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

const databaseUrl = env('DATABASE_URL');
const directUrl = env('DIRECT_URL');

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: databaseUrl,
    // Only set shadowDatabaseUrl if DIRECT_URL is different from DATABASE_URL
    // For introspection (db pull), shadow database is not needed when they're the same
    ...(directUrl && directUrl !== databaseUrl
      ? { shadowDatabaseUrl: directUrl }
      : {}),
  },
});
